# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(356, 405)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 361, 411))
        self.label.setStyleSheet("background-image: url(:/newPrefix/fondologin.jpeg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/fondologin.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 0, 331, 61))
        self.label_2.setStyleSheet("font: 87 25pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.leUsuario = QtWidgets.QLineEdit(Dialog)
        self.leUsuario.setGeometry(QtCore.QRect(90, 90, 191, 20))
        self.leUsuario.setObjectName("leUsuario")
        self.lePass = QtWidgets.QLineEdit(Dialog)
        self.lePass.setGeometry(QtCore.QRect(90, 130, 191, 20))
        self.lePass.setObjectName("lePass")
        self.btnIngresar = QtWidgets.QPushButton(Dialog)
        self.btnIngresar.setGeometry(QtCore.QRect(150, 280, 91, 23))
        self.btnIngresar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar.setObjectName("btnIngresar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Inicio de Sesion"))
        self.leUsuario.setPlaceholderText(_translate("Dialog", "Ingresa tu Usuario"))
        self.lePass.setPlaceholderText(_translate("Dialog", "Ingresa tu Contraseña"))
        self.btnIngresar.setText(_translate("Dialog", "INGRESAR"))
import loginprueba_rc
