# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(336, 451)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 341, 451))
        self.label.setStyleSheet("background-image: url(:/newPrefix/interfaz.jpeg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/interfaz.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.btnIngresar = QtWidgets.QPushButton(Dialog)
        self.btnIngresar.setGeometry(QtCore.QRect(90, 50, 171, 51))
        self.btnIngresar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar.setObjectName("btnIngresar")
        self.btnIngresar_2 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_2.setGeometry(QtCore.QRect(90, 120, 171, 51))
        self.btnIngresar_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_2.setObjectName("btnIngresar_2")
        self.btnIngresar_3 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_3.setGeometry(QtCore.QRect(90, 200, 171, 51))
        self.btnIngresar_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_3.setObjectName("btnIngresar_3")
        self.btnIngresar_4 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_4.setGeometry(QtCore.QRect(90, 270, 171, 51))
        self.btnIngresar_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_4.setObjectName("btnIngresar_4")
        self.btnIngresar_5 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_5.setGeometry(QtCore.QRect(90, 340, 171, 51))
        self.btnIngresar_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_5.setObjectName("btnIngresar_5")
        self.btnIngresar_6 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_6.setGeometry(QtCore.QRect(10, 390, 71, 51))
        self.btnIngresar_6.setStyleSheet("background-color: rgb(124, 231, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_6.setObjectName("btnIngresar_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnIngresar.setText(_translate("Dialog", "Registro de Entrada"))
        self.btnIngresar_2.setText(_translate("Dialog", "Consultar Entradas"))
        self.btnIngresar_3.setText(_translate("Dialog", "Ver Graficas"))
        self.btnIngresar_4.setText(_translate("Dialog", " Horarios de Turno"))
        self.btnIngresar_5.setText(_translate("Dialog", "Cambiar Visibilidad V/F"))
        self.btnIngresar_6.setText(_translate("Dialog", "Back"))
import prueba_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
